### ISSUE TITLE
sharing preprocessing files

### ISSUE THREAD

**Issue by lqzhao** [ShengyuH/Scene-Recognition-in-3D#2]
Hi，it's a wonderful method.

Would you mind sharing preprocessing files via a google drive or baidu disk link？
That would help me to easily reproduce your method and implemented my own method.
Thanks.

**Comment by ShengyuH** [comment]
hi, 

Thanks for your interest. This work was done almost 2 years ago during my Master study, by then the code was actually quite messy :), so it's difficult for me to find the exact script. I hope this small script helps to some extent, please see: https://github.com/ShengyuH/Scene-Recognition-in-3D/issues/1.

Best,
Shengyu
